version: "3.8"

services:
  mc:
    image: projectozone3:latest
    environment:
      eula: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/app/minecraft/
      - ./eula.txt:/app/minecraft/eula.txt
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}